blogs/urls.py
from django.urls import path
from blogs.views import post_comment_create_and_list_view,PostDeleteView,PostUpdateView,like_unlike_post,post_comment_list_view

app_name = 'blogs'

urlpatterns = [
    path('', post_comment_list_view, name='main-post-view'),
    path('<pk>/', post_comment_create_and_list_view, name='main-detail'),
    path('Liked/',like_unlike_post,name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('cart/', cart , name='cart'),
    path('checkout/', checkout , name='checkout'),
    path('update_item/', updateItem , name='update_item'),
    path('process_order/', processOrder , name='process_order'),
    path('product/<int:pk>/', ProductDetailView, name='product_detail'),
]

web_design/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from web_design import views as web_view
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', web_view.home_page, name="home"),
    path('about/', web_view.about_page, name="about"),
    path('contact/', web_view.contact_page, name="contact"),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('register/',user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.htm'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.htm'), name="logout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/about.htm
{% extends 'base.htm' %} {% load static %} {% load crispy_forms_tags %} 
{% block title %} About {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="hero">
  <div class="h1 center">About</div>
</div>

<div class="container">
  <div class="pt-5">
    <div class="row pb-5">
      <div class="col-8 p-2">
        <div class="h2 font-weight-bold">Our Story</div>
        <p class="pt-2 text-justify font-weight-light">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris
          consequat consequat enim, non auctor massa ultrices non. Morbi sed
          odio massa. Quisque at vehicula tellus, sed tincidunt augue. Orci
          varius natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Maecenas varius egestas diam, eu sodales metus
          scelerisque congue. Pellentesque habitant morbi tristique senectus et
          netus et malesuada fames ac turpis egestas. Maecenas gravida justo eu
          arcu egestas convallis. Nullam eu erat bibendum, tempus ipsum eget,
          dictum enim. Donec non neque ut enim dapibus tincidunt vitae nec
          augue. Suspendisse potenti. Proin ut est diam. Donec condimentum
          euismod tortor, eget facilisis diam faucibus et. Morbi a tempor elit.
        </p>
        <p class="pt-2 text-justify font-weight-light">
          Donec gravida lorem elit, quis condimentum ex semper sit amet. Fusce
          eget ligula magna. Aliquam aliquam imperdiet sodales. Ut fringilla
          turpis in vehicula vehicula. Pellentesque congue ac orci ut gravida.
          Aliquam erat volutpat. Donec iaculis lectus a arcu facilisis, eu
          sodales lectus sagittis. Etiam pellentesque, magna vel dictum rutrum,
          neque justo eleifend elit, vel tincidunt erat arcu ut sem. Sed rutrum,
          turpis ut commodo efficitur, quam velit convallis ipsum, et maximus
          enim ligula ac ligula.
        </p>
        <p class="pt-2 text-justify font-weight-light">
          Any questions? Let us know in store at 8th floor, 379 Hudson St, New
          York, NY 10018 or call us on (+1) 96 716 6879
        </p>
      </div>
      <div class="col-4 p-4">
          <img class="img" src="{% static 'images/waneella.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="row">
      <div class="col-4">
        <img class="img" src="{% static 'images/127.jpg' %}" alt="">
      </div>
      <div class="col-8">
        <div class="h2 font-weight-bold">Our Mission</div>
        <p class="pt-2 p-1 text-justify font-weight-light">
          Mauris non lacinia magna. Sed nec lobortis dolor. Vestibulum rhoncus
          dignissim risus, sed consectetur erat. Pellentesque habitant morbi
          tristique senectus et netus et malesuada fames ac turpis egestas.
          Nullam maximus mauris sit amet odio convallis, in pharetra magna
          gravida. Praesent sed nunc fermentum mi molestie tempor. Morbi vitae
          viverra odio. Pellentesque ac velit egestas, luctus arcu non, laoreet
          mauris. Sed in ipsum tempor, consequat odio in, porttitor ante. Ut
          mauris ligula, volutpat in sodales in, porta non odio. Pellentesque
          tempor urna vitae mi vestibulum, nec venenatis nulla lobortis. Proin
          at gravida ante. Mauris auctor purus at lacus maximus euismod.
          Pellentesque vulputate massa ut nisl hendrerit, eget elementum libero
          iaculis.
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/main/contact.htm
{% extends 'base.htm' %} {% load static %} {% load crispy_forms_tags %} {% block title %} Contact {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'contact.css' %}" />
<div class="hero">
  <div class="h1 center">Contact</div>
</div>

<div class="container pb-5">
  <div class="border p-5 mt-5">
    <div class="p-5">
      <div class="pb-5">
        <div class="row">
          <div class="col-6">
            <span class="material-icons">location_on</span>
            <span class="h5 pl-1">Address</span>
          </div>
        </div>
        <div class="row">
          <div class="col-7 h6 text-justify font-weight-light pl-5">
            Coza Store Center 8th floor, 379 Hudson St, New York, NY 10018 US
          </div>
        </div>
      </div>
      <div class="pb-5">
        <div class="row">
          <div class="col-6">
            <span class="material-icons">phone</span>
            <span class="h5 pl-1 pb-1">Lets Talk</span>
          </div>
        </div>
        <div class="row">
          <div class="col-6 h6 text-justify font-weight-light pl-5">
            +1 800 1236879
          </div>
        </div>
      </div>
      <div class="">
        <div class="row">
          <div class="col-6">
            <span class="material-icons">mail_outline</span>
            <span class="h5 pl-1 pb-1">Sale Support</span>
          </div>
        </div>
        <div class="row">
          <div class="col-6 h6 text-justify font-weight-light pl-5">
            contact@example.com
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/main/home.htm
{% extends 'base.htm' %} {% load static %} {% block title %} Home {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'home.css' %}" />

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'images/david.jpg' %}" alt="First slide" style="height: 600px;">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-left">First slide label</h5>
        <p class="text-left">Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        <a href="{% url 'products:product_list' %}" class="btn btn-primary float-left">Shop Now</a>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/luca.jpg' %}" alt="Second slide" style="height: 600px;">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="{% url 'products:product_list' %}"  class="btn btn-primary">Shop Now</a>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/timon.jpg' %}" alt="Third slide" style="height: 600px;">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-right">Third slide label</h5>
        <p class="text-right">Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        <a href="{% url 'products:product_list' %}"  class="btn btn-primary float-right">Shop Now</a>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

templates/main/navbar.htm
{% load static %}
{% url 'home' as path_to_home %}
{% url 'products:product_list' as path_to_shop %}
{% url 'blogs:main-post-view' as path_to_blogs %}
{% url 'about' as path_to_about %}
{% url 'contact' as path_to_contact %}

<link rel="stylesheet" href="{% static 'navbar.css' %}" />
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="navbar-brand h1 m-3">
      <a href="{% url 'home' %}">
      <span class="font-weight-bold">COZA</span>
      <span class="font-weight-light">STORE</span>
      </a>
    </div>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse pl-3" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ml-5">
        {% if user.is_authenticated %}
        <li class="nav-item pr-3">
          <a class="nav-link font-weight-normal {% if request.path == path_to_home %}active{% endif %}" href="{{path_to_home}}">Home </a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link font-weight-normal {% if request.path == path_to_shop %}active{% endif %}" href="{{path_to_shop}}">Shop </a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link font-weight-normal {% if request.path == path_to_blogs %}active{% endif %}" href="{{path_to_blogs}}">Blog</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link font-weight-normal {% if request.path == path_to_about %}active{% endif %}" href="{{path_to_about}}">About</a>
        </li>
        <li class="nav-item pr-3 ">
          <a class="nav-link font-weight-normal {% if request.path == path_to_contact %}active{% endif %}" href="{{path_to_contact}}">Contact</a>
        </li>
        {% endif %}
      </ul>
      
      <form class="form-inline navbar-nav  my-2 my-lg-0">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=""
              >Welcome, {{user.username}}</a
            >
          </li>
          <a href="{% url 'products:cart' %}">
            <span id="cart-icon" class="material-icons-outlined pt-2 pl-3"> shopping_cart </span>
          </a>
          <p id="cart-total" class="pt-1">{{cartItems}}</p>
          {% else %}

          <li class="nav-item">
            <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
          </li>
          {% endif %}
        </ul>
      </form>
    </div>
  </div>
</nav>