blogs/urls.py
from django.urls import path
from blogs.views import post_comment_create_and_list_view,PostDeleteView,PostUpdateView,like_unlike_post,post_comment_list_view

app_name = 'blogs'

urlpatterns = [
    path('', post_comment_list_view, name='main-post-view'),
    path('<pk>/', post_comment_create_and_list_view, name='main-detail'),
    path('Liked/',like_unlike_post,name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

web_design/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from web_design import views as web_view
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', web_view.home_page, name="home"),
    path('about/', web_view.about_page, name="about"),
    path('contact/', web_view.contact_page, name="contact"),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('register/',user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.htm'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.htm'), name="logout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from products.models import Category
from users.models import Profile


class Post(models.Model):
    title = models.CharField(max_length=200, default="")
    picture = models.ImageField(upload_to='images', blank=True)
    body = models.TextField()
    liked = models.ManyToManyField(Profile, default=None, blank=True,related_name='likes')
    author = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True,related_name='posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='categories' )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.pk}-{self.body}"

    def get_liked(self):
        return self.liked.all()

    @property
    def like_count(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count() 

    def get_user_liked(self, user):
        pass

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like','Like'),
    ('Unlike','Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"
    
    

blogs/forms.py
from django import forms
from blogs.models import Post, Comment

class PostModelForm(forms.ModelForm):
    body = forms.CharField(label='content',widget=forms.Textarea(attrs={'rows':2}))

    class Meta:
        model = Post
        fields = ('title','body','category','picture')

class CommentModelForm(forms.ModelForm):
    comment = forms.CharField(label='',widget=forms.Textarea(attrs={'placeholder':'Add a comment...','rows':1}))

    class Meta:
        model = Comment
        fields = ('comment',)

blogs/views.py
from django.shortcuts import render, redirect
from .models import Post,Like
from users.models import Profile
from  .forms import PostModelForm, CommentModelForm
from django.http import JsonResponse
from django.core import serializers
from django.views.generic import UpdateView,DeleteView,DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from products.models import *



def post_comment_list_view(request):
    qs = Post.objects.all().order_by('-created')
    profile = Profile.objects.get(user=request.user)
    categories = Category.objects.all()
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_add =False
    profile = Profile.objects.get(user=request.user)

    if 'submit_p_form' in request.POST:
        print(request.user)
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_add = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()

    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']

    context = {
        'qs': qs,
        'profile':profile,
        'p_form':p_form,
        'c_form':c_form,
        'post_add':post_add,
        'items': items, 
        'order': order, 
        'cartItems': cartItems,
        'categories': categories,
    }

    return render(request,'blogs/view_blog.htm',context)


def post_comment_create_and_list_view(request,pk):
    qs = Post.objects.filter(id=pk)
    profile = Profile.objects.get(user=request.user)
    categories = Category.objects.all()
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_add =False
    profile = Profile.objects.get(user=request.user)

    if 'submit_p_form' in request.POST:
        print(request.user)
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_add = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()

    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']

    context = {
        'qs': qs,
        'profile':profile,
        'p_form':p_form,
        'c_form':c_form,
        'post_add':post_add,
        'items': items, 
        'order': order, 
        'cartItems': cartItems,
        'categories': categories,
    }

    return render(request,'blogs/blog_detail.htm',context)



def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'

            post_obj.save()
            like.save()


    return redirect('blogs:main-detail')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blogs/confirm_del.htm'
    success_url = reverse_lazy('blogs:main-post-view')

    def get_object(self , *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'your need to be the author of the post in order to delete')
        return obj
    

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'blogs/update.htm'
    success_url = reverse_lazy('blogs:main-post-view')

    def form_valid(self,form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None,"You need to be the author of the post in order to update it")
            return super().form_invalid(form)

blogs/templates/blogs/blog_detail.htm
{% extends 'base.htm' %} {% load static %} {% load crispy_forms_tags %} {% block title %} Blogs {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'blog_main.css' %}" />
<div class="hero">
  <div class="h1 center">Blogs</div>
</div>

<div class="container">
    <div class="row">
        <div class="col-9">
            <div class="mt-5">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="home">Home</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'blogs:main-post-view' %}">Blog</a></li>
                  <li class="breadcrumb-item active" aria-current="page">{% for obj in qs %} {{obj.title}} {% endfor %}</li>
                </ol>
              </nav>
            </div>
            <div class="mt-2">
                {% for obj in qs %}
                <div class=" p-4 mb-3">
                    <div class="p-4 mb-3">
                        <div class="row">
                          <div class="row w-100">
                            {% if obj.picture %}
                            <div class="col-12">
                              <img src="{{obj.picture.url}}" class="imageContent" />
                            </div>
                            {% endif %}
                          </div>
                        </div>
                        <div class="row mt-2">
                            <div class="mt-2">
                                <p class="font-weight-normal">
                                  By {{ obj.author.user }} | {{obj.created|timesince}} | {{obj.category}} |
                                  {{obj.num_comments}} comments
                                </p>
                              </div>
                            
                          </div>
                        <div class="row mt-4 mb-3">
                          <div class="h4 font-weight-bold">{{obj.title}}</div>
                        </div>
                        <div class="row mb-2">
                          <div
                            class="h6 font-weight-light text-justify  d-inline-block"
                            style="max-width: 1000px"
                          >
                            {{obj.body}}
                          </div>
                        </div>
                        
                      </div>
                      <div class="mt-4">
                          <div class="h5">LEAVE A COMMENT</div>
                          <div class="h6 mt-3">{{obj.num_comments}} comments</div>
                      </div>
                  <div class="pt-3">
                    <div>
                      {% if obj.comment_set.all %} {% for c in obj.comment_set.all %}
                      <div class="card pt-2 pl-3 pb-2">
                        <span
                          ><img class="avatar" src="{{c.user.avatar.url}}" /> 
                          {{ c.user.user }} - {{c.created|timesince}} : {{ c.comment }}</span
                        >
                      </div>
                      {% endfor %} {% endif %}
                    </div>
                    <form action="" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="post_id" value="{{obj.id}}" />
                      {{c_form|crispy}}
                      <button class="btn btn-primary float-left" name="submit_c_form">
                        Send
                      </button>
                    </form>
                  </div>
                </div>
              {% endfor %}
            </div>
        </div>
        <div class="col-3">
            <div class="mt-5">
            {% for obj in qs %}
            {% if 'admin' == user.username %}
            <a
              class="btn btn-secondary btn-sm mt-1 mb-1"
              href="{% url 'blogs:post-update' obj.id %}"
              >Update</a
            >
            <a
              class="btn btn-danger btn-sm mt-1 mb-1"
              href="{% url 'blogs:post-delete' obj.id %}"
              >Delete</a
            >
            {% else %}
            
            {% endif %}
            {% endfor %}
        </div>
        </div>
    </div>
</div>
{% endblock content %}

blogs/templates/blogs/confirm_del.htm
{% extends 'base.htm' %}

{% block title %}
    delete post
{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class="messages">
                    <div class="harder">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="mt-5">
    {% if not messages %}
        <div class="card p-5">
            <h3>Delete Post?</h3>
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete post?</p>
                <button type="submit" class="btn btn-danger">Yes</button>
                <a href="{% url 'blogs:main-post-view'%}" class="btn btn-secondary">cancel</a>
            </form>
        </div>
    {% endif %}
</div>
</div>
{% endblock content %}

blogs/templates/blogs/update.htm
{% extends 'base.htm' %}
{% load crispy_forms_tags %}
{% block title %}
    update post
{% endblock title %}

{% block content %}
    <div class="card p-5">
        <h3>Update Post</h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}

blogs/templates/blogs/view_blog.htm
{% extends 'base.htm' %} {% load static %} {% load crispy_forms_tags %} {% block title %} Blogs {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'blog_main.css' %}" />
<div class="hero">
  <div class="h1 center">Blogs</div>
</div>

<div class="container">
  <div class="row mt-5">
    <div class="col-8">
      <div class="tab-content" id="nav-tabContent">
        <div
          class="tab-pane fade show active"
          id="list-home"
          role="tabpanel"
          aria-labelledby="list-home-list"
        >
          {% for obj in qs %}
          <div class="p-4 mb-3">
            <div class="row">
              <div class="row w-100">
                {% if obj.picture %}
                <div class="col-12">
                  <img src="{{obj.picture.url}}" class="imageContent" />
                </div>
                {% endif %}
              </div>
            </div>
            <div class="row mt-4 mb-3">
              <div class="h4 font-weight-bold">{{obj.title}}</div>
            </div>
            <div class="row mb-2">
              <div
                class="h6 font-weight-light text-justify text-truncate d-inline-block"
                style="max-width: 1000px"
              >
                {{obj.body}}
              </div>
            </div>
            <div class="row">
              <div class="mt-2">
                  <p class="font-weight-normal">
                    By {{ obj.author.user }} | {{obj.category}} |
                    {{obj.num_comments}} comments
                  </p>
                </div>
              <div class="col">
                <div class="float-right">
                  <a href="{% url 'blogs:main-detail' obj.id %}" class="btn font-weight-bold btn-secondary">CONTINUE READING  </a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        {% for obj in qs %}
        <div
          class="tab-pane fade"
          id="list-{{obj.category}}"
          role="tabpanel"
          aria-labelledby="list-{{obj.category}}-list"
        >
          {% for cate in qs %} {% if cate.category == obj.category %}
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page">{{obj.category}}</li>
            </ol>
          </nav>
          
          <div class="p-4 mb-3">
            <div class="row">
              <div class="row w-100">
                {% if obj.picture %}
                <div class="col-12">
                  <img src="{{obj.picture.url}}" class="imageContent" />
                </div>
                {% endif %}
              </div>
            </div>
            <div class="row mt-4 mb-3">
              <div class="h4 font-weight-bold">{{obj.title}}</div>
            </div>
            <div class="row mb-2">
              <div
                class="h6 font-weight-light text-justify text-truncate d-inline-block"
                style="max-width: 1000px"
              >
                {{obj.body}}
              </div>
            </div>
            <div class="row">
              <div class="mt-2">
                  <p class="font-weight-normal">
                    By {{ obj.author.user }} | {{obj.category}} |
                    {{obj.num_comments}} comments
                  </p>
                </div>
              <div class="col">
                <div class="float-right">
                  <a href="{% url 'blogs:main-detail' obj.id %}" class="btn font-weight-bold btn-secondary">CONTINUE READING  </a>
                </div>
              </div>
            </div>
          </div>
          {% endif %} {% endfor %}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-4 pl-5">
      {% if 'admin' == user.username %}
      {% if post_add %}
      <div class="alert alert-success" role="alert">Post Added!</div>
      {% endif %}
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{p_form|crispy}}
        <div class="text-center">
          <button type="submit" class="btn btn-success" name="submit_p_form">
            Send Post
          </button>
        </div>
      </form>
      {% endif %}
      <div class="categories mb-5">
        <div class="mt-5">
          <div class="h5 font-weight-light">Categories</div>
          <div class="mt-4">
            <div class="list-group" id="list-tab" role="tablist">
              {% for category in categories %}
              <a
                class="list-group-item list-group-item-action"
                id="list-{{category.name}}-list"
                data-toggle="list"
                href="#list-{{category.name}}"
                role="tab"
                aria-controls="{{category.name}}"
                >{{category.name}}</a
              >
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}