blogs/urls.py
from django.urls import path
from blogs.views import post_comment_create_and_list_view,PostDeleteView,PostUpdateView,like_unlike_post,post_comment_list_view

app_name = 'blogs'

urlpatterns = [
    path('', post_comment_list_view, name='main-post-view'),
    path('<pk>/', post_comment_create_and_list_view, name='main-detail'),
    path('Liked/',like_unlike_post,name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    path('', product_list, name="product_list"),
    path('cart/', cart , name='cart'),
    path('checkout/', checkout , name='checkout'),
    path('update_item/', updateItem , name='update_item'),
    path('process_order/', processOrder , name='process_order'),
    path('product/<int:pk>/', ProductDetailView, name='product_detail'),
]

web_design/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from web_design import views as web_view
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', web_view.home_page, name="home"),
    path('about/', web_view.about_page, name="about"),
    path('contact/', web_view.contact_page, name="contact"),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('register/',user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.htm'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.htm'), name="logout"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile



class Category(models.Model):
    name = models.TextField(max_length=200)
    slug = models.SlugField(max_length=40)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False,null=True,blank=True)
    image= models.ImageField(null=True, blank=True)
    content = models.TextField(max_length=1000, default="")
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100,null=True)

    def __str__(self):
        return str(self.id)

 
    @property
    def shipping(self):
        shipping = False
        orderitem = self.orderitem_set.all()
        for i in orderitem:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_item(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
   
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_add = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShoppingAddress(models.Model):
    customer = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

    



    
    

products/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

products/views.py
from django.shortcuts import render,get_object_or_404
from .forms import UserRegisterForm
from .models import Category, Product
from django.http import HttpResponseRedirect,Http404
from products.models import *
from django.http import JsonResponse
import json
import datetime

def product_list(request):
    categories = Category.objects.all()
    products = Product.objects.all() 

    pro_category = Product.objects.filter(category=None).order_by('name')


    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']


    context = {
        'categories': categories,
        'products': products,
        'pro_category': pro_category,
        'items': items, 
        'order': order, 
        'cartItems': cartItems
    }

    return render(request, 'products/product_list.htm',context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.htm', {'form': form})

    
def ProductDetailView(request, pk):
    try:
        p = Product.objects.get(pk=pk)
    except Product.DoesNotExist:
        raise Http404("does not exist")

    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']

    context = {'items': items, 'order': order, 'cartItems': cartItems, 'product': p}
    return render(request, 'products/productDetail.htm', context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'products/cart.htm', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_item': 0, 'shipping': False}
        cartItems = order['get_cart_item']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'products/checkout.htm', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('productId:', productId)

    customer = request.user.profile
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.profile
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True
        order.save()

        if order.shipping == True:
            ShoppingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode'],
            )

    else:
        print('User is not logged in')
    return JsonResponse('Payment', safe=False)

products/templates/products/cart.htm
{% extends 'base.htm' %} {% load static %} {% block title %} Cart {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}" />
<div class="container">

<div class="row mt-5">
  <div class="col-lg-12">
    <div class="box-element">
        <a class="btn btn-outline-dark mt-2" href="{% url 'products:product_list' %}">&#x2190; Continue Shopping</a>
        <br>
        <br>
        <table class="table">
            <tr>
                <th><h5>Items: <strong>{{order.get_cart_item}}</strong></h5></th>
                <th><h5>Total:<strong> ${{order.get_cart_total}}</strong></h5></th>
                <th>
                    <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'products:checkout' %}">Checkout</a>
                </th>
            </tr>
        </table>
    </div>

    <br />
    <div class="box-element">
        <div class="cart-row">
            <div style="flex:2"></div>
            <div style="flex:2"><strong>Item</strong></div>
            <div style="flex:1"><strong>Price</strong></div>
            <div style="flex:1"><strong>Quantity</strong></div>
            <div style="flex:1"><strong>Total</strong></div>
        </div>
        {% for item in items %}
        <div class="cart-row">
            <div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
            <div style="flex:2"><p>{{item.product.name}}</p></div>
            <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
            <div style="flex:1">
                <p class="quantity">{{item.quantity}}</p>
                <div class="quantity">
                    <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'img/arrow-up.png' %}">
                    <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'img/arrow-down.png' %}">
                </div>
            </div>
            <div style="flex:1"><p>${{item.get_total}}</p></div>
        </div>
        {% endfor %}
        </div>
  </div>
</div>
</div>
{% endblock content %}

products/templates/products/checkout.htm
{% extends 'base.htm' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}" />
<div class="container">
<div class="row mt-5">
  <div class="col-lg-6">
    <div class="box-element" id="form-wrapper">
      <form id="form">
        {% csrf_token %}
        <div id="user-info">
          <div class="form-field">
            <input
              required
              class="form-control"
              type="text"
              name="name"
              placeholder="Name.."
            />
          </div>
          <div class="form-field">
            <input
              required
              class="form-control"
              type="email"
              name="email"
              placeholder="Email.."
            />
          </div>
        </div>

        <div id="shipping-info">
          <hr />
          <p>Shipping Information:</p>
          <hr />
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="address"
              placeholder="Address.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="city"
              placeholder="City.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="state"
              placeholder="State.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="zipcode"
              placeholder="Zip code.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="country"
              placeholder="Zip code.."
            />
          </div>
        </div>

        <hr />
        <input
          id="form-button"
          class="btn btn-success btn-block"
          type="submit"
          value="Continue"
        />
      </form>
    </div>
    <br />
    <div class="box-element hidden" id="payment-info">
      <small>Paypal Option</small>
      <button id="make-payment">Make Payment</button>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'products:cart' %}"
        >&#x2190; Back to Cart</a
      >
      <hr />
      <h3>Order Summary</h3>
      <hr />
      {% for item in items %}
      <div class="cart-row">
        <div style="flex: 2">
          <img class="row-image" src="{{item.product.image.url}}" />
        </div>
        <div style="flex: 2"><p>{{item.product.name}}</p></div>
        <div style="flex: 1"><p>${{item.product.price}}</p></div>
        <div style="flex: 1"><p>x{{item.quantity}}</p></div>
      </div>
      {% endfor %}
      <h5>Items: {{order.get_cart_item}}</h5>
      <h5>Total: ${{order.get_cart_total}}</h5>
    </div>
  </div>
</div>
</div>


<script type="text/javascript">
  var shipping = "{{order.shipping}}";
  var total = "{{order.get_cart_total}}";

  if (shipping == "False") {
    document.getElementById("shipping-info").innerHTML = "";
  }

  if (user != "AnonymousUser") {
    document.getElementById("user-info").innerHTML = ""
  }

  if (shipping == "False" && user != "AnonymousUser") {
    document.getElementById("form-wrapper").classList.add("hidden");
    document.getElementById("payment-info").classList.remove("hidden");
  }

  var form = document.getElementById("form");

  csrftoken = form.getElementsByTagName("input")[0].value
  console.log('Newtoken:', form.getElementsByTagName("input")[0].value)

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    console.log("Form Submitted...");
    document.getElementById("form-button").classList.add("hidden");
    document.getElementById("payment-info").classList.remove("hidden");
  });

  document
    .getElementById("make-payment")
    .addEventListener("click", function (e) {
      submitFormData();
    });

  function submitFormData() {
    console.log("payment button clicked");

    var userFormData = {
      name: null,
      email: null,
      total: total,
    };
    var shippingInfo = {
      address: null,
      city: null,
      state: null,
      zipcode: null,
    };

    if (shipping != 'False'){
        shippingInfo.address = form.address.value
        shippingInfo.city = form.city.value
        shippingInfo.state = form.state.value
        shippingInfo.zipcode = form.zipcode.value
    }
    if (user == 'AnonymousUser'){
        userFormData.name = form.name.value
        userFormData.email = form.email.value
    }

    var url = "/products/process_order/"
    fetch(url,{
        method:'POST',
        headers:{
            'Content-Type' : 'application/json',
            'X-CSRFToken': csrftoken,

        },
        body:JSON.stringify({'form':userFormData,'shipping':shippingInfo}),

    })
    .then((respones)=>respones.json())
    .then((data)=>{
        console.log('Success', data);
        alert('Transaction Completed');
        window.location.href="{% url 'products:product_list' %}"
    })
  }
</script>
{% endblock content %}

products/templates/products/productDetail.htm
{% extends 'base.htm' %} {% load static %} {% block title %}  {{product.name}} {% endblock title %} {% block content %}
<div class="container">
  <div class="mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'products:product_list' %}">Shop</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{product.name}}</li>
    </ol>
  </nav>
</div>
  <div class="mt-3">
  <div class="card p-5">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <img class="thumbnail card" src="{{product.image.url}}" />
        </div>
      </div>
      <div class="col-9 float-left">
        <div class="h2 font-weight-normal">{{product.name}}</div>
        <div class="price font-weight-bold h5">
          ${{product.price}}
        </div>
        <br />
        <div class="h6 font-weight-light">{{product.content}}</div>
        <br />
        <button
          data-product="{{product.id}}"
          data-action="add"
          class="btn btn-info add-btn update-cart btn-sm"
        >
          Add to Cart
        </button>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock content %}

products/templates/products/product_list.htm
{% extends 'base.htm' %} {% load static %} {% block title %} Shop {% endblock title %} {% block content %}
<div class="container">
  <ul class="nav nav-pills mb-3 mt-4" id="pills-tab" role="tablist">
    <li class="nav-item m-3">
      <a
        class="active"
        id="pills-all-product-tab"
        data-toggle="pill"
        href="#pills-all-product"
        role="tab"
        aria-controls="pills-all-product"
        aria-selected="true"
        >All Product</a
      >
    </li>
    {% for category in categories %}
    <li class="nav-item m-3">
      <a
        class=""
        id="pills-{{category.name}}-tab"
        data-toggle="pill"
        href="#pills-{{category.name}}"
        role="tab"
        aria-controls="pills-{{category.name}}"
        aria-selected="false"
        >{{category.name}}</a
      >
    </li>
    {% endfor %}
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div
      class="tab-pane fade show active"
      id="pills-all-product"
      role="tabpanel"
      aria-labelledby="pills-home-tab"
    >
      <div>
        <div class="row">
          {% for product in products %}
          <div class="col-3">
            <div class="card mb-3">
              <img class="card-img-top" src="{{product.image.url}}" />
              <div class="card-body">
                <h6 class="card-title">{{product.name}}</h6>
                <p class="card-text">$ {{product.price}}</p>
                <div class="row">
                    <div class="col">
                      <button
                        data-product="{{product.id}}"
                        data-action="add"
                        class="btn btn-info add-btn update-cart btn-sm"
                      >
                        Add to Cart
                      </button>
    
                      <a
                        class="btn btn-outline-info btn-sm"
                        href="{% url 'products:product_detail' product.id %}"
                        >View</a
                      >
                    </div>
                  </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% for product in products %}
    <div
      class="tab-pane fade"
      id="pills-{{product.category}}"
      role="tabpanel"
      aria-labelledby="pills-{{product.category}}-tab"
    >
      <div class="row">
        {% for pro in products %} {% if product.category == pro.category %}
        <div class="col-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{pro.image.url}}" />
            <div class="card-body">
              <h6 class="card-title">{{pro.name}}</h6>
              <p class="card-text">$ {{pro.price}}</p>
              <div class="row">
                <div class="col">
                  <button
                    data-product="{{product.id}}"
                    data-action="add"
                    class="btn btn-info add-btn update-cart btn-sm"
                  >
                    Add to Cart
                  </button>

                  <a
                    class="btn btn-outline-info btn-sm"
                    href="{% url 'products:product_detail' product.id %}"
                    >View</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %} {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}